### ISSUE TITLE
只能支持UFI103s吗？

### ISSUE THREAD

**Issue by gdzhujun** [zfdx123/UFI-OpenWRT#1]
### Describe the bug

只能支持UFI103s吗？

### OpenWrt version

只能支持UFI103s吗？

### OpenWrt target/subtarget

只能支持UFI103s吗？

### Device

只能支持UFI103s吗？

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by zfdx123** [comment]
不是，001b 001c 等应该都没有问题，因为没有sim支持

**Comment by zfdx123** [comment]
现在还在完善阶段，还不能启用大部分功能，尽快填坑

**Comment by gdzhujun** [comment]
编译过不去

**Comment by zfdx123** [comment]
需要本地编译

**Comment by gdzhujun** [comment]
是本地编译的

**Comment by zfdx123** [comment]
log

**Comment by zfdx123** [comment]
设备烧坏了，停止开发
